// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAed4xUCp_0UUFgnmG-NRZ-eaBDW_s5o7I',
    appId: '1:580253366003:web:e74638f3314fda2e4c2986',
    messagingSenderId: '580253366003',
    projectId: 'chat-app-5f3b5',
    authDomain: 'chat-app-5f3b5.firebaseapp.com',
    storageBucket: 'chat-app-5f3b5.appspot.com',
    measurementId: 'G-XESZ635N8C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCRGCfknfmspY-oH2TVnTdmBe_XtuKUcVA',
    appId: '1:580253366003:android:d28972926c83b5b44c2986',
    messagingSenderId: '580253366003',
    projectId: 'chat-app-5f3b5',
    storageBucket: 'chat-app-5f3b5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAJOVRtxeD_qE4JLAV-ryHrXN4yLz1-O88',
    appId: '1:580253366003:ios:b49af43f72495a2e4c2986',
    messagingSenderId: '580253366003',
    projectId: 'chat-app-5f3b5',
    storageBucket: 'chat-app-5f3b5.appspot.com',
    iosClientId: '580253366003-8b1266iolgepq42rhp5kasp2qgf19jkv.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseChatapp',
  );
}
